---
repos:
  - repo: https://github.com/soerenschneider/pre-commit-hooks
    rev: v1.5.2
    hooks:
      - id: tf-fmt
      - id: tf-checkov
      - id: tflint
      - id: trivy
      - id: gitleaks
